name: Copilot Bot

on:
    push:
        branches:
            - main
        paths:
            - "copilot-bot/src/**"
    pull_request:
        branches:
            - main
        paths:
            - "copilot-bot/src/**"

jobs:
    pipeline:
        uses: ./.github/workflows/bot-pipeline.yml
        with:
            bot-name: copilot-bot
        secrets: inherit
