name: Deploy Angry Bot

on: 
    workflow_dispatch:
        inputs:
            version:
                description: Version of the Bot to deploy.
                required: true
                default: 'latest'


defaults:
    run:
        working-directory: angry-bot
      
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - id: ssh
                uses: invi5H/ssh-action@v1
                with:
                    SSH_HOST: ${{ secrets.SSH_HOST }}
                    SSH_PORT: ${{ secrets.SSH_PORT }}
                    SSH_USER: ${{ secrets.SSH_USER }}
                    SSH_KEY: ${{ secrets.SSH_KEY }}
            - run: ssh ${{ steps.ssh.output.SERVER }} cd ${{ secrets.COMPOSE_LOCATION }} && docker-compose down && docker-compose pull && docker-compose up -d