name: Deploy Angry Bot

on: 
    workflow_dispatch:
        inputs:
            version:
                description: Version of the Bot to deploy.
                required: true
                default: 'latest'


defaults:
    run:
        working-directory: angry-bot
      
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Update deployment
              uses: appleboy/ssh-action@v0.1.6
              with:
                host: ${{ secrets.SSH_HOST }}
                port: ${{ secrets.SSH_PORT }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_KEY }}
                script: cd $ {{ secrets.COMPOSE_LOCATION }} &&
                    docker-compose down &&
                    docker-compose pull &&
                    docker-compose up -d
