name: Frens Bot

on:
    push:
        branches:
            - main
        paths:
            - "frens-bot/src/**"
            - "frens-bot/package.json"
    pull_request:
        branches:
            - main
        paths:
            - "frens-bot/src/**"
            - "frens-bot/package.json"

jobs:
    pipeline:
        uses: ./.github/workflows/bot-pipeline.yml
        with:
            bot-name: frens-bot
        secrets: inherit
