name: Shared

on:
    push:
        branches:
            - main
        paths:
            - "shared/lib/**"
    pull_request:
        branches:
            - main
        paths:
            - "shared/lib/**"

defaults:
    run:
        working-directory: shared

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6
            - uses: actions/setup-node@v6
              with:
                node-version: 24
                cache: 'pnpm'
            - run: pnpm install
            - name: Run biome check
              run: pnpm run check
    Typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: pnpm/action-setup@v6
            - uses: actions/setup-node@v6
              with:
                node-version: 24
                cache: 'pnpm'
            - run: pnpm install
            - name: Run typechecking
              run: pnpm run typecheck
