name: Shared

on:
    pull_request:
        branches:
            - master
        paths:
            - "shared/lib/**"
    push:
        branches:
            - master
        paths:
            - "shared/lib/**"

defaults:
    run:
        working-directory: shared

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "yarn"
                  cache-dependency-path: "yarn.lock"
            - run: yarn install --frozen-lockfile
            - name: Run linting
              run: yarn lint
    Typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "yarn"
                  cache-dependency-path: "yarn.lock"
            - run: yarn install --frozen-lockfile
            - name: Run typechecking
              run: yarn typecheck
