name: Shared

on:
    pull_request:
        branches:
            - master
        paths:
            - "shared/lib/**"
    push:
        branches:
            - master
        paths:
            - "shared/lib/**"

defaults:
    run:
        working-directory: shared

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
            - run: bun install
            - name: Run biome check
              run: bun run check
    Typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
            - run: bun install
            - name: Run typechecking
              run: bun run typecheck
