name: Willhaben Bot

on:
    push:
        branches:
            - main
        paths:
            - "willhaben-bot/src/**"
            - "willhaben-bot/package.json"
    pull_request:
        branches:
            - main
        paths:
            - "willhaben-bot/src/**"
            - "willhaben-bot/package.json"

jobs:
    pipeline:
        uses: ./.github/workflows/bot-pipeline.yml
        with:
            bot-name: willhaben-bot
        secrets: inherit
